import { AllianceType, StationType, MonitorStatusType, DSStationStatus } from '../fms/fms-api';
import type { FieldMonitorData } from '../fms/fms-signalr';

export const Blue1Default: FieldMonitorData = {
	teamNumber: 5678,
	alliance: AllianceType.Blue,
	station: StationType.Station1,
	connection: false,
	dsLinkActive: false,
	radioLink: false,
	rioLink: false,
	linkActive: false,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Unknown
};

export const Blue2Default: FieldMonitorData = {
	teamNumber: 9876,
	alliance: AllianceType.Blue,
	station: StationType.Station2,
	connection: true,
	dsLinkActive: false,
	radioLink: false,
	rioLink: false,
	linkActive: false,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Unknown
};

export const Blue3Default: FieldMonitorData = {
	teamNumber: 4321,
	alliance: AllianceType.Blue,
	station: StationType.Station3,
	connection: true,
	dsLinkActive: false,
	radioLink: false,
	rioLink: false,
	linkActive: false,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Waiting
};

export const Red1Default: FieldMonitorData = {
	teamNumber: 2468,
	alliance: AllianceType.Red,
	station: StationType.Station1,
	connection: true,
	dsLinkActive: true,
	radioLink: false,
	rioLink: false,
	linkActive: false,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Unknown
};

export const Red2Default: FieldMonitorData = {
	teamNumber: 1357,
	alliance: AllianceType.Red,
	station: StationType.Station2,
	connection: true,
	dsLinkActive: true,
	radioLink: true,
	rioLink: true,
	linkActive: false,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Unknown
};

export const Red3Default: FieldMonitorData = {
	teamNumber: 3242,
	alliance: AllianceType.Red,
	station: StationType.Station3,
	connection: true,
	dsLinkActive: true,
	radioLink: true,
	rioLink: true,
	linkActive: true,
	isEnabled: false,
	isAuto: false,
	isBypassed: false,
	isEStopPressed: false,
	isEStopped: false,
	battery: 0,
	monitorStatus: MonitorStatusType.Unknown,
	averageTripTime: 0,
	lostPackets: 0,
	signal: 0,
	dataRateTotal: 0,
	stationStatus: DSStationStatus.Unknown
};
